export const FETCH_NOWPLAYING_MOVIES = 'FETCH_NOWPLAYING_MOVIES';

export const FETCH_UPCOMING_MOVIES = 'FETCH_UPCOMING_MOVIES';

export const FETCH_POPULAR_MOVIES = 'FETCH_POPULAR_MOVIES';

export const FETCH_TOP_RATED_MOVIES = 'FETCH_TOP_RATED_MOVIES';

export const SEARCH_DATA = 'SEARCH_DATA';

export const GET_MOVIE_DETAILS = 'GET_MOVIE_DETAILS';